{{ if or (and (not .Values.embeddedEtcd.enabled) (not .Values.headless) (not .Values.etcd.disabled)) .Values.embeddedEtcd.migrateFromEtcd }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-etcd-headless
  namespace: {{ .Release.Namespace }}
  labels:
    app: vcluster-etcd
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
  {{- $annotations := merge .Values.globalAnnotations .Values.etcd.serviceAnnotations }}
  {{- if $annotations }}
  annotations:
{{ toYaml $annotations | indent 4 }}
  {{- end }}
spec:
  publishNotReadyAddresses: true
  ports:
    - name: etcd
      port: 2379
      targetPort: 2379
      protocol: TCP
    - name: peer
      port: 2380
      targetPort: 2380
      protocol: TCP
  clusterIP: None
  selector:
    app: vcluster-etcd
    release: "{{ .Release.Name }}"
{{ end }}
